enum HttpStatusCode {
  SUCCESS_OK = 200,
  SUCCESS_CREATED = 201,
  CLIENT_ERROR_BADREQUEST = 400,
  CLIENT_ERROR_UNAUTHORIZED = 401,
  CLIENT_ERROR_FORBIDDEN = 403,
  CLIENT_ERROR_NOTFOUND = 404,
  CLIENT_ERROR_CONFLICT = 409,
  SERVER_ERROR_INTERNAL = 500,
}

export default HttpStatusCode;
